### ISSUE TITLE
transcript links point to the wrong episode

### ISSUE THREAD

**Issue by porglezomp** [emily-signet/curiosity#2]
Reproducing for myself:
- Search "tarp"
- Click on the first transcript title "[Marielda 01: The City of Light Pt. 1](https://docs.google.com/document/d/159OscYtwecH661AxBD6kpERKJgyqFio1rUlJCrDBmH0)"
- That's a link to COUNTER/Weight 39

**Comment by porglezomp** [comment]
I just tried using the API manually and it looks like those have the correct IDs so I guess it's a frontend bug

**Comment by kore-signet** [comment]
I can't seem to reproduce this on firefox; what version are you using? And which query type?

**Comment by porglezomp** [comment]
I'm using firefox, using https://fatt.fish, exact match search.

But! I had the wrong instructions: narrowed it down, it actually happens when:
- I search for one search term
- I search for a second search term (or change filter settings, etc.) and get different results
- The headings are still linking to the urls from the first search results

Concrete example:
- Search "any sound"
- First result is CW 39
- Links correctly to CW 39
- Search "tarp" in the same session
- First result is Marielda 01
- Links to CW 39 instead

**Comment by kore-signet** [comment]
aha! i can reproduce it now, thank you!

**Comment by kore-signet** [comment]
fixed in 34f4f0c, will be up whenever github actions decides to run

**Comment by kore-signet** [comment]
fix up!
