### ISSUE TITLE
Missing results

### ISSUE THREAD

**Issue by porglezomp** [emily-signet/curiosity#5]
- https://fatt.fish/
- exact match
- search for "any sound"
- The final result, [Bluff City 19: Messy Business Pt. 4](https://docs.google.com/document/d/1HJ65OWAbbOFwBE01-LYl8AT3O2T2xbb9WIYMWK7G05g) shows no excerpts
- Looking at the actual transcript, there are two matches on the same line:
> AUSTIN: Any- <ins>any sound!</ins> He can do <ins>any sound</ins>.

![image](https://github.com/emily-signet/curiosity/assets/1690225/000e750d-f4d8-49f5-957f-f06b1a5678bf)

**Comment by kore-signet** [comment]
will take a look!

**Comment by kore-signet** [comment]
at first glance i think it may be because of any being present earlier in the sentence

**Comment by kore-signet** [comment]
fixed in latest release!
