### ISSUE TITLE
Mobile: search input fields line wrapping

### ISSUE THREAD

**Issue by porglezomp** [emily-signet/curiosity#7]
The season search and query type are stuck on the same line:

![IMG_6564](https://github.com/emily-signet/curiosity/assets/1690225/e7f76b44-c2ed-46ac-bdae-4afaf808390c)

**Comment by kore-signet** [comment]
I think both this and #7 should be fixed by the latest update; keeping the issue open for now as testing for mobile is Hard and so it may not be fixed on your particular phone

**Comment by porglezomp** [comment]
Verified fixed for me. Thank you!
